In [ ]:
# mLinear Algebra with Annuity Matrices
#Matrices: Represent withdrawal charges as array
import numpy as np

# AccuMax 7 withdrawal charges over 7 years: [9%,8%,7%,6%,5%,4%,3%]
charges = np.array([0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03])
premiums = np.array([10000, 50000, 100000])  # Sample premiums
penalties = premiums.reshape(-1,1) * charges  # Matrix multiplication for penalties
print("Penalties per year for different premiums:\n", penalties)

# Vectors: Rate vectors for strategies.
#Why? Applies math to real Athene charges/rates.
low_rates = np.array([0.88, 3.65, 4.35, 0.80, 1.50, 1.45, 0.0345])  # AccuMax 7 low band
high_rates = np.array([0.93, 3.85, 4.60, 0.85, 1.60, 1.55, 0.0375])
diff = high_rates - low_rates
print("High vs Low Band Rate Differences:", diff)

Penalties per year for different premiums:
 [[ 900.  800.  700.  600.  500.  400.  300.]
 [4500. 4000. 3500. 3000. 2500. 2000. 1500.]
 [9000. 8000. 7000. 6000. 5000. 4000. 3000.]]
High vs Low Band Rate Differences: [0.05  0.2   0.25  0.05  0.1   0.1   0.003]
